solve issue 545
ddeboer/imap pull request #546
Opened 2022-08-24 07:27 UTC by ivanghisleni

Related to Issue: https://github.com/ddeboer/imap/issues/545

2022-08-24 08:08 UTC, Slamdunk commented
Hi, can you also add tests please?

2022-08-24 09:25 UTC, ivanghisleni commented
@Slamdunk I'm generating test 😅

2022-08-24 09:28 UTC, Slamdunk commented
Nice. You can also run the build locally, so the development feedback loop gets much faster, see https://github.com/ddeboer/imap#contributing-run-the-build-locally

2022-08-24 09:40 UTC, Slamdunk requested changes

2022-08-24 09:40 UTC, Slamdunk commented on src/Message/Headers.php
> +            } catch (\Exception $e) {
```suggestion
            } catch (\Ddeboer\Imap\Exception\UnsupportedCharsetException $e) {
```
Let just catch the only known types of Exception

2022-08-26 11:06 UTC, ivanghisleni commented
@Slamdunk I didn't change anything in AbstractPart.php where pipeline fails.... 😅

2022-08-26 12:23 UTC, Slamdunk approved these changes

2022-08-26 12:24 UTC, merged